### ISSUE TITLE
python tools/waf --help

### ISSUE THREAD

**Issue by SourceLink** [foxBMS/foxbms#2]
➜  foxbms git:(master) ✗ python tools/waf --help
Waf: The wscript in '/home/sourcelink/work/test/foxbms' is unreadable
Traceback (most recent call last):
  File "/home/sourcelink/work/test/foxbms/tools/.waf-2.0.15-ff6573b86ad5ff5d449c8852ad58b8bc/waflib/Scripting.py", line 102, in waf_entry_point
    set_main_module(wscript)
  File "/home/sourcelink/work/test/foxbms/tools/.waf-2.0.15-ff6573b86ad5ff5d449c8852ad58b8bc/waflib/Scripting.py", line 142, in set_main_module
    Context.g_module=Context.load_module(file_path)
  File "/home/sourcelink/work/test/foxbms/tools/.waf-2.0.15-ff6573b86ad5ff5d449c8852ad58b8bc/waflib/Context.py", line 355, in load_module
    exec(compile(code,path,'exec'),module.__dict__)
  File "/home/sourcelink/work/test/foxbms/wscript", line 122
    conf.fatal(f'path to foxbms must not contain spaces'

How to solve this problem?

**Comment by foxBMS** [comment]
Dear @SourceLink,

It seems that you are using a python2 interpreter, but since version 1.5.0 foxBMS requires a python3 interpreter.
This is not clearly mentioned in the documentation. We will update the documentation about that with the next release.

Sorry for the inconvenience and best regards,
The foxBMS Team

**Comment by SourceLink** [comment]
Traceback (most recent call last):
  File "/home/sourcelink/work/test/foxbms/tools/.waf3-2.0.15-ff6573b86ad5ff5d449c8852ad58b8bc/waflib/Scripting.py", line 102, in waf_entry_point
    set_main_module(wscript)
  File "/home/sourcelink/work/test/foxbms/tools/.waf3-2.0.15-ff6573b86ad5ff5d449c8852ad58b8bc/waflib/Scripting.py", line 142, in set_main_module
    Context.g_module=Context.load_module(file_path)
  File "/home/sourcelink/work/test/foxbms/tools/.waf3-2.0.15-ff6573b86ad5ff5d449c8852ad58b8bc/waflib/Context.py", line 355, in load_module
    exec(compile(code,path,'exec'),module.__dict__)
  File "/home/sourcelink/work/test/foxbms/wscript", line 122
    conf.fatal(f'path to foxbms must not contain spaces'

replaced with python3, the situation is still the same, how to do?

**Comment by foxBMS** [comment]
Dear @SourceLink,

would you please verify that you are using python3.6 or greater.
foxBMS uses [f-strings](https://docs.python.org/3/whatsnew/3.6.html#pep-498-formatted-string-literals) in its python scripts and these are only supported in python versions greater 3.6.

Best regards,
The foxBMS Team
